Gemini Model addition for classification task
autodistill/autodistill pull request #165
Opened 2024-06-21 11:23 UTC by lab176344

Added gemini base model for classification

2024-06-21 13:08 UTC, capjamesg approved these changes

2024-06-21 13:08 UTC, capjamesg requested changes

2024-06-22 08:13 UTC, lab176344 commented on docs/base_models/gemini.md
> +To use EvaCLIP with autodistill, you need to install the following dependency:
Done =)

2024-06-24 12:01 UTC, capjamesg approved these changes

2024-06-24 12:02 UTC, merged